name: dejacode

x-description: "Build override: builds the app image from source instead of using the pre-built image"

services:
  web:
    build: .

  worker:
    build: .

  scheduler:
    build: .
