# Generated by Django 6.0.4 on 2026-07-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0002_alter_columntemplate_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('action', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('reachability', 'Reachability Analysis'), ('forensics', 'Forensic Analysis')], max_length=30)),
                ('timeline_days', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(choices=[('package', 'Package'), ('vulnerability', 'Vulnerability'), ('product', 'Product')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_points', to='reporting.query')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('precedence', models.PositiveIntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('default_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='triage_rules.triagedecision')),
            ],
            options={
                'ordering': ('-precedence', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower values are evaluated first.')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='triage_rules.ruleset')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='triage_rules.triagedecision')),
            ],
            options={
                'ordering': ('priority', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.PositiveSmallIntegerField(choices=[(0, 'False'), (1, 'True')])),
                ('decision_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage_rules.decisionpoint')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='triage_rules.rule')),
            ],
            options={
                'unique_together': {('rule', 'decision_point')},
            },
        ),
    ]
