# Generated by Django 6.0.6 on 2026-07-03 13:38

from django.db import migrations


def migrate_webhooks_to_subscriptions(apps, schema_editor):
    Webhook = apps.get_model("notification", "Webhook")
    WebhookSubscription = apps.get_model("notification", "WebhookSubscription")

    subscriptions = [
        WebhookSubscription(
            dataspace=webhook.dataspace,
            target_url=webhook.target,
            is_active=webhook.is_active,
            event=webhook.event,
            extra_payload=webhook.extra_payload,
            extra_headers=webhook.extra_headers,
        )
        for webhook in Webhook.objects.select_related("dataspace").iterator()
    ]

    WebhookSubscription.objects.bulk_create(subscriptions)


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0002_webhooksubscription_webhookdelivery"),
    ]

    operations = [
        migrations.RunPython(
            migrate_webhooks_to_subscriptions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
