# Generated by Django 6.0.6 on 2026-07-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_migrate_webhook_to_webhooksubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
