# Generated by Django 4.2.7 on 2023-11-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reporting", "0001_initial"),
        ("dje", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataspaceconfiguration",
            name="homepage_layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a general purpose Card layout that provides timely query results on the DejaCode homepage to your application users.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                serialize=False,
                to="reporting.cardlayout",
            ),
        ),
        migrations.AddField(
            model_name="dejacodeuser",
            name="dataspace",
            field=models.ForeignKey(
                help_text="A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.",
                on_delete=django.db.models.deletion.PROTECT,
                to="dje.dataspace",
            ),
        ),
        migrations.AddField(
            model_name="dejacodeuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="dejacodeuser",
            name="homepage_layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a Card layout that provides the query results on the DejaCode homepage that are useful and interesting to you.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                serialize=False,
                to="reporting.cardlayout",
            ),
        ),
        migrations.AddField(
            model_name="dejacodeuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externalsource",
            unique_together={("dataspace", "label"), ("dataspace", "uuid")},
        ),
        migrations.AlterUniqueTogether(
            name="externalreference",
            unique_together={("dataspace", "uuid")},
        ),
    ]
