# Generated by Django 5.0.3 on 2024-05-08 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dje", "0002_initial"),
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dejacodeuser",
            name="homepage_layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a Card layout that provides the query results on the DejaCode homepage that are useful and interesting to you.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                serialize=False,
                to="reporting.cardlayout",
            ),
        ),
    ]
