# Generated by Django 5.0.6 on 2024-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0003_alter_dejacodeuser_homepage_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspace',
            name='vulnerabilities_updated_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when the local vulnerability database was last updated. ', null=True, verbose_name='Last vulnerability data update'),
        ),
    ]
