# Generated by Django 5.0.9 on 2024-12-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0004_dataspace_vulnerabilities_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='vulnerabilities_risk_threshold',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Enter a risk value between 0.0 and 10.0. This threshold helps prioritize and control the level of attention to vulnerabilities.', max_digits=3, null=True),
        ),
    ]
