# Generated by Django 5.2.4 on 2025-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0007_dejacodeuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='github_token',
            field=models.CharField(blank=True, help_text='Personal access token (PAT) or GitHub App token used to authenticateAPI requests for this integration. Keep this token secure.', max_length=255, verbose_name='GitHub token'),
        ),
    ]
