# Generated by Django 5.2.4 on 2025-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0008_dataspaceconfiguration_github_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='gitlab_token',
            field=models.CharField(blank=True, help_text="Personal access token (PAT) used to authenticate API requests for the GitLab integration. This token must have 'api' scope. Keep this token secure.", max_length=255, verbose_name='GitLab token'),
        ),
    ]
