# Generated by Django 5.2.4 on 2025-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0009_dataspaceconfiguration_gitlab_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='jira_token',
            field=models.CharField(blank=True, help_text='API token generated from your Atlassian account, used to authenticate API requests to Jira Cloud. Keep this token secure.', max_length=255, verbose_name='Jira API token'),
        ),
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='jira_user',
            field=models.CharField(blank=True, help_text='The email address associated with your Jira account. Used together with the API token to authenticate API requests.', max_length=255, verbose_name='Jira user email'),
        ),
    ]
