# Generated by Django 5.2.4 on 2025-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0010_dataspaceconfiguration_jira_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='forgejo_token',
            field=models.CharField(blank=True, help_text='Personal access token (PAT) used to authenticate API requests for the Forgejo integration. This token must have sufficient permissions to create and update issues. Keep this token secure.', max_length=255, verbose_name='Forgejo token'),
        ),
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='sourcehut_token',
            field=models.CharField(blank=True, help_text='Access token used to authenticate API requests for the SourceHut integration. This token must have permissions to create and update tickets. Keep this token secure.', max_length=255, verbose_name='SourceHut token'),
        ),
    ]
