# Generated by Django 5.2.4 on 2025-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0011_dataspaceconfiguration_forgejo_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataspaceconfiguration',
            name='sourcehut_token',
            field=models.CharField(blank=True, help_text='Access token used to authenticate API requests for the SourceHut integration. This token must have permissions to create and update tickets. Keep this token secure.', max_length=2048, verbose_name='SourceHut token'),
        ),
    ]
