# Generated by Django 6.0.2 on 2026-02-23 19:49

from django.db import migrations
from django.contrib.auth.hashers import make_password


def migrate_api_tokens(apps, schema_editor):
    """Migrate existing plain-text DRF tokens to the new hashed APIToken model."""
    OldToken = apps.get_model("authtoken", "Token")
    APIToken = apps.get_model("dje", "APIToken")

    PREFIX_LENGTH = 8

    for old_token in OldToken.objects.select_related("user").all():
        plain_key = old_token.key
        APIToken.objects.create(
            user=old_token.user,
            prefix=plain_key[:PREFIX_LENGTH],
            key_hash=make_password(plain_key),
            created=old_token.created,
        )


def reverse_migrate_api_tokens(apps, schema_editor):
    """Reverse migration: remove all migrated tokens."""
    APIToken = apps.get_model("dje", "APIToken")
    APIToken.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0013_apitoken'),
    ]

    operations = [
        migrations.RunPython(migrate_api_tokens, reverse_migrate_api_tokens),
    ]
