# Generated by Django 6.0.4 on 2026-04-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0014_apitoken_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataspaceconfiguration',
            name='purldb_api_key',
            field=models.CharField(blank=True, help_text="If your organization's private PurlDB instance requires an API key for access, provide it here. If not, you can leave this field empty.", max_length=255, verbose_name='PurlDB API key'),
        ),
        migrations.AlterField(
            model_name='dataspaceconfiguration',
            name='scancodeio_api_key',
            field=models.CharField(blank=True, help_text="If your organization's private ScanCode.io instance requires an API key for access, provide it here. Otherwise, you can leave this field empty.", max_length=255, verbose_name='ScanCode.io API key'),
        ),
        migrations.AlterField(
            model_name='dataspaceconfiguration',
            name='vulnerablecode_api_key',
            field=models.CharField(blank=True, help_text='If your private VulnerableCode instance requires an API key for access, input it here. If not, you can leave this field blank.', max_length=255, verbose_name='VulnerableCode API key'),
        ),
    ]
