# Generated by Django 6.0.6 on 2026-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0015_alter_dataspaceconfiguration_purldb_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataspaceconfiguration',
            name='policy_rules_config',
            field=models.JSONField(blank=True, default=dict, help_text='Override default policy rule settings for this dataspace. '),
        ),
    ]
