# Generated by Django 5.2.9 on 2026-02-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_library', '0002_initial'),
        ('policy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseprofile',
            name='default_usage_policy',
            field=models.ForeignKey(blank=True, help_text='Default usage policy to be assigned to a license when using this license profile.', limit_choices_to={'content_type__app_label': 'license_library', 'content_type__model': 'license'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.usagepolicy'),
        ),
    ]
