# Generated by Django 6.0.2 on 2026-03-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_library', '0003_licenseprofile_default_usage_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_profile',
            field=models.ForeignKey(blank=True, help_text='License profile: a selection of license tags and their values, identified by a descriptive name, in order to provide a convenient way to assign a set of tag values to a license. A "Tag" identifies a frequently encountered obligation, restriction, or other notable characteristic of license terms. Note that individual tag value assignments may vary by license.', null=True, on_delete=django.db.models.deletion.PROTECT, to='license_library.licenseprofile', verbose_name='License profile'),
        ),
    ]
