# Generated by Django 6.0.6 on 2026-08-14 15:02

import django.contrib.postgres.fields
import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
        ('product_portfolio', '0019_productaffectedbyvulnerability_detected_date'),
        ('vulnerabilities', '0010_api_v3_remove_old_fields'),
        ('workflow', '0003_externalissuelink_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('state', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('resolved_with_pedigree', 'Resolved With Pedigree'), ('exploitable', 'Exploitable'), ('in_triage', 'In Triage'), ('false_positive', 'False Positive'), ('not_affected', 'Not Affected')], help_text='Declares the current state of an occurrence of a vulnerability, after automated or manual analysis.', max_length=25)),
                ('justification', models.CharField(blank=True, choices=[('code_not_present', 'Code Not Present'), ('code_not_reachable', 'Code Not Reachable'), ('protected_at_perimeter', 'Protected At Perimeter'), ('protected_at_runtime', 'Protected At Runtime'), ('protected_by_compiler', 'Protected By Compiler'), ('protected_by_mitigating_control', 'Protected By Mitigating Control'), ('requires_configuration', 'Requires Configuration'), ('requires_dependency', 'Requires Dependency'), ('requires_environment', 'Requires Environment')], help_text='The rationale of why the impact analysis state was asserted.', max_length=35)),
                ('responses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('can_not_fix', 'Can Not Fix'), ('rollback', 'Rollback'), ('update', 'Update'), ('will_not_fix', 'Will Not Fix'), ('workaround_available', 'Workaround Available')], max_length=20), blank=True, help_text='A response to the vulnerability by the manufacturer, supplier, or project responsible for the affected component or service. More than one response is allowed. Responses are strongly encouraged for vulnerabilities where the analysis state is exploitable.', null=True)),
                ('detail', models.TextField(blank=True, help_text='Detailed description of the impact including methods used during assessment. If a vulnerability is not exploitable, this field should include specific details on why the component or service is not impacted by this vulnerability.')),
                ('name', models.CharField(help_text='Short name identifying this analysis preset.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of when and why this preset is applied.')),
                ('is_reachable', models.BooleanField(blank=True, help_text='Reachability value to set on the analysis. Leave blank to leave the field unchanged.', null=True)),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('dataspace', 'name'), ('dataspace', 'uuid')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TriageRuleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(help_text='Short name identifying this triage ruleset.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the purpose or scope of this ruleset.')),
                ('recommended_action', models.CharField(blank=True, help_text="Remediation action recommended when this ruleset's conditions are met.", max_length=50)),
                ('precedence', models.PositiveIntegerField(help_text='When multiple rulesets are assigned to a product and produce different actions, the one with the highest precedence takes effect.')),
                ('enabled', models.BooleanField(default=True, help_text='Activate or deactivate this ruleset without deleting it.')),
                ('rules_config', models.JSONField(blank=True, default=dict, help_text='Active rules for this ruleset, keyed by rule type.')),
                ('analysis_preset', models.ForeignKey(blank=True, help_text='Optional preset automatically applied to matching vulnerability analyses. Only applied when no human-owned analysis exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_rulesets', to='vulnerabilities_triage.analysispreset')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('request_template', models.ForeignKey(blank=True, help_text='Optional product-type request template. When set, the triage engine automatically opens a request for each newly detected vulnerability match.', limit_choices_to={'content_type__app_label': 'product_portfolio', 'content_type__model': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_rulesets', to='workflow.requesttemplate')),
            ],
            options={
                'ordering': ('-precedence', 'name'),
                'unique_together': {('dataspace', 'name'), ('dataspace', 'precedence'), ('dataspace', 'uuid')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('recommended_action', models.CharField(blank=True, help_text='Recommended action captured at the time of evaluation.', max_length=50)),
                ('matched_rules', models.JSONField(default=list, help_text='Rules that fired for this vulnerability during evaluation.')),
                ('detected_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when this recommendation was first generated.')),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Date and time of the last evaluation.')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product', models.ForeignKey(help_text='The product this recommendation applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='product_portfolio.product')),
                ('request', models.ForeignKey(blank=True, help_text='Request automatically opened by the triage engine for this vulnerability match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_records', to='workflow.request')),
                ('vulnerability', models.ForeignKey(help_text='The vulnerability that triggered this recommendation.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='vulnerabilities.vulnerability')),
                ('ruleset', models.ForeignKey(help_text='The ruleset that produced this action.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='vulnerabilities_triage.triageruleset')),
            ],
            options={
                'ordering': ['-detected_date'],
                'unique_together': {('dataspace', 'uuid'), ('vulnerability', 'product', 'ruleset')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTriageRuleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product', models.ForeignKey(help_text='The product this ruleset is activated for.', on_delete=django.db.models.deletion.CASCADE, related_name='product_triage_rulesets', to='product_portfolio.product')),
                ('ruleset', models.ForeignKey(help_text='The ruleset to evaluate against this product.', on_delete=django.db.models.deletion.CASCADE, related_name='product_triage_rulesets', to='vulnerabilities_triage.triageruleset')),
            ],
            options={
                'ordering': ['-ruleset__precedence'],
                'unique_together': {('dataspace', 'uuid'), ('product', 'ruleset')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
    ]
