# Generated by Django 6.0.6 on 2026-07-30 14:29

import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRuleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(help_text='Short name identifying this triage ruleset within the dataspace.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the purpose or scope of this ruleset.')),
                ('precedence', models.PositiveIntegerField(default=100, help_text='When multiple rulesets are assigned to a product and produce different actions, the one with the highest precedence takes effect.')),
                ('enabled', models.BooleanField(default=True, help_text='Activate or deactivate this ruleset without deleting it.')),
                ('rules_config', models.JSONField(blank=True, default=dict, help_text='Active rules for this ruleset, keyed by rule type. Each entry may include is_active, threshold, and parameters.')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
            ],
            options={
                'ordering': ('-precedence', 'name'),
                'unique_together': {('dataspace', 'name'), ('dataspace', 'uuid')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
    ]
