# Generated by Django 6.0.6 on 2026-08-11 10:36

import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
        ('product_portfolio', '0019_productaffectedbyvulnerability_detected_date'),
        ('vulnerabilities', '0010_api_v3_remove_old_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageRuleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(help_text='Short name identifying this triage ruleset.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the purpose or scope of this ruleset.')),
                ('action', models.CharField(blank=True, help_text="Action recommended when this ruleset's conditions are met.", max_length=50)),
                ('precedence', models.PositiveIntegerField(default=100, help_text='When multiple rulesets are assigned to a product and produce different actions, the one with the highest precedence takes effect.')),
                ('enabled', models.BooleanField(default=True, help_text='Activate or deactivate this ruleset without deleting it.')),
                ('rules_config', models.JSONField(blank=True, default=dict, help_text='Active rules for this ruleset, keyed by rule type.')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
            ],
            options={
                'ordering': ('-precedence', 'name'),
                'unique_together': {('dataspace', 'name'), ('dataspace', 'uuid')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('action', models.CharField(help_text='Recommended action captured at the time of evaluation.', max_length=50)),
                ('matched_rules', models.JSONField(default=list, help_text='Rules that fired for this vulnerability during evaluation.')),
                ('detected_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when this recommendation was first generated.')),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Date and time of the last evaluation.')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product', models.ForeignKey(help_text='The product this recommendation applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='product_portfolio.product')),
                ('vulnerability', models.ForeignKey(help_text='The vulnerability that triggered this recommendation.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='vulnerabilities.vulnerability')),
                ('ruleset', models.ForeignKey(help_text='The ruleset that produced this action.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='vulnerabilities_triage.triageruleset')),
            ],
            options={
                'ordering': ['-detected_date'],
                'unique_together': {('dataspace', 'uuid'), ('vulnerability', 'product', 'ruleset')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTriageRuleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product', models.ForeignKey(help_text='The product this ruleset is activated for.', on_delete=django.db.models.deletion.CASCADE, related_name='product_triage_rulesets', to='product_portfolio.product')),
                ('ruleset', models.ForeignKey(help_text='The ruleset to evaluate against this product.', on_delete=django.db.models.deletion.CASCADE, related_name='product_triage_rulesets', to='vulnerabilities_triage.triageruleset')),
            ],
            options={
                'ordering': ['-ruleset__precedence', 'ruleset__name'],
                'unique_together': {('dataspace', 'uuid'), ('product', 'ruleset')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
    ]
