# Generated by Django 6.0.6 on 2026-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities_triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageruleset',
            name='action',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade Package'), ('apply_patch', 'Apply Patch'), ('forensic_analysis', 'Forensic Analysis'), ('reachability_analysis', 'Reachability Analysis'), ('change_config', 'Change Configuration'), ('replace_package', 'Replace Package'), ('notify', 'Notify'), ('create_request', 'Create DejaCode Request')], help_text="Action recommended when this ruleset's conditions are met.", max_length=50),
        ),
        migrations.AlterField(
            model_name='triageruleset',
            name='name',
            field=models.CharField(help_text='Short name identifying this triage ruleset.', max_length=100),
        ),
        migrations.AlterField(
            model_name='triageruleset',
            name='rules_config',
            field=models.JSONField(blank=True, default=dict, help_text='Active rules for this ruleset, keyed by rule type.'),
        ),
    ]
