# Generated by Django 6.0.6 on 2026-08-13 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities_triage', '0002_analysispreset_triageruleset_analysis_preset'),
        ('workflow', '0003_externalissuelink_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='request',
            field=models.ForeignKey(blank=True, help_text='Request automatically opened by the triage engine for this vulnerability match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_records', to='workflow.request'),
        ),
        migrations.AddField(
            model_name='triageruleset',
            name='request_template',
            field=models.ForeignKey(blank=True, help_text='Optional product-type request template. When set, the triage engine automatically opens a request for each newly detected vulnerability match.', limit_choices_to={'content_type__app_label': 'product_portfolio', 'content_type__model': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_rulesets', to='workflow.requesttemplate'),
        ),
    ]
