# Generated by Django 6.0.6 on 2026-08-06 06:38

import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
        ('product_portfolio', '0019_productaffectedbyvulnerability_detected_date'),
        ('vulnerabilities_triage', '0002_triageruleset_action_alter_triageruleset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('action', models.CharField(choices=[('upgrade', 'Upgrade Package'), ('apply_patch', 'Apply Patch'), ('forensic_analysis', 'Forensic Analysis'), ('reachability_analysis', 'Reachability Analysis'), ('change_config', 'Change Configuration'), ('replace_package', 'Replace Package'), ('notify', 'Notify'), ('create_request', 'Create DejaCode Request')], help_text='Recommended action at the time of evaluation.', max_length=50)),
                ('matched_rules', models.JSONField(default=list, help_text='List of rule types that detected violations during this evaluation.')),
                ('detected_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when this action was first recommended.')),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Date and time of the last evaluation.')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product', models.ForeignKey(help_text='The product against which this ruleset was evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_decisions', to='product_portfolio.product')),
                ('ruleset', models.ForeignKey(help_text='The ruleset that produced this action.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_decisions', to='vulnerabilities_triage.triageruleset')),
            ],
            options={
                'ordering': ['-detected_date'],
                'unique_together': {('dataspace', 'uuid'), ('product', 'ruleset')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
    ]
