# Generated by Django 6.0.6 on 2026-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities_triage', '0003_triagedecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagedecision',
            name='action',
            field=models.CharField(help_text='Recommended action at the time of evaluation.', max_length=50),
        ),
        migrations.AlterField(
            model_name='triageruleset',
            name='action',
            field=models.CharField(blank=True, help_text="Action recommended when this ruleset's conditions are met.", max_length=50),
        ),
    ]
