# Generated by Django 6.0.6 on 2026-08-06 12:37

import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
        ('product_portfolio', '0019_productaffectedbyvulnerability_detected_date'),
        ('vulnerabilities_triage', '0004_alter_triagedecision_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackageTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('action', models.CharField(help_text='Recommended action captured at the time of evaluation.', max_length=50)),
                ('matched_rules', models.JSONField(default=list, help_text='Rules that fired for this package during evaluation.')),
                ('detected_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when this recommendation was first generated.')),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='Date and time of the last evaluation.')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product_package', models.ForeignKey(help_text='The specific package usage that triggered this recommendation.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='product_portfolio.productpackage')),
                ('ruleset', models.ForeignKey(help_text='The ruleset that produced this action.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='vulnerabilities_triage.triageruleset')),
            ],
            options={
                'ordering': ['-detected_date'],
                'unique_together': {('dataspace', 'uuid'), ('product_package', 'ruleset')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='TriageDecision',
        ),
    ]
