# Generated by Django 6.0.6 on 2026-08-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
        ('product_portfolio', '0019_productaffectedbyvulnerability_detected_date'),
        ('vulnerabilities_triage', '0005_productpackagetriage_delete_triagedecision'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPackageTriage',
            new_name='TriageRecord',
        ),
    ]
