# Generated by Django 6.0.6 on 2026-08-11 04:40

import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
        ('product_portfolio', '0019_productaffectedbyvulnerability_detected_date'),
        ('vulnerabilities_triage', '0006_rename_productpackagetriage_triagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTriageRuleset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product', models.ForeignKey(help_text='The product this ruleset is activated for.', on_delete=django.db.models.deletion.CASCADE, related_name='product_triage_rulesets', to='product_portfolio.product')),
                ('ruleset', models.ForeignKey(help_text='The ruleset to evaluate against this product.', on_delete=django.db.models.deletion.CASCADE, related_name='product_triage_rulesets', to='vulnerabilities_triage.triageruleset')),
            ],
            options={
                'ordering': ['-ruleset__precedence', 'ruleset__name'],
                'unique_together': {('dataspace', 'uuid'), ('product', 'ruleset')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
    ]
