#
# Copyright (c) nexB Inc. and others. All rights reserved.
# DejaCode is a trademark of nexB Inc.
# SPDX-License-Identifier: AGPL-3.0-only
# See https://github.com/aboutcode-org/dejacode for support or download.
# See https://aboutcode.org for more information about AboutCode FOSS projects.
#


PROGRAMMING_LANGUAGES = (
    "4th Dimension/4D",
    "ABAP",
    "ABC",
    "ActionScript",
    "Ada",
    "Agilent VEE",
    "Algol",
    "Alice",
    "Angelscript",
    "ANTLR",
    "Apex",
    "APL",
    "AppleScript",
    "Arc",
    "Arduino",
    "ASP",
    "AspectJ",
    "Assembly",
    "ATLAS",
    "Augeas",
    "AutoHotkey",
    "AutoIt",
    "AutoLISP",
    "Automator",
    "Avenue",
    "Awk",
    "Bash",
    "Batchfile",
    "Visual Basic",
    "bc",
    "BCPL",
    "BETA",
    "BlitzMax",
    "Boo",
    "Bourne Shell",
    "Bro",
    "C",
    "C Shell",
    "C#",
    "C++",
    "C++/CLI",
    "C-Omega",
    "Caml",
    "Ceylon",
    "CFML",
    "cg",
    "Ch",
    "Chapel",
    "CHILL",
    "CIL",
    "CL (OS/400)",
    "Clarion",
    "Clean",
    "Clipper",
    "Clojure",
    "CLU",
    "COBOL",
    "Cobra",
    "CoffeeScript",
    "ColdFusion",
    "COMAL",
    "Common Lisp",
    "Coq",
    "Crystal",
    "CSS",
    "cT",
    "Curl",
    "D",
    "Dart",
    "DCL",
    "DCPU-16 ASM",
    "Delphi/Object Pascal",
    "DiBOL",
    "Dylan",
    "E",
    "eC",
    "Ecl",
    "ECMAScript",
    "EGL",
    "Eiffel",
    "Elixir",
    "Elm",
    "Emacs Lisp",
    "Erlang",
    "Etoys",
    "Euler",
    "Euphoria",
    "EXEC",
    "Expect",
    "F#",
    "Factor",
    "Falcon",
    "Fancy",
    "Fantom",
    "Felix",
    "Fish",
    "Flex",
    "Forth",
    "Fortran",
    "Fortran 90",
    "Fortress",
    "FreePascal",
    "Frege",
    "GAS",
    "Gambas",
    "GDScript",
    "GLSL (OpenGL Shading Language)",
    "GNU Octave",
    "Go",
    "Google AppsScript",
    "Gosu",
    "Groovy",
    "Haskell",
    "Haxe",
    "Heron",
    "HTML",
    "HPL",
    "Hy",
    "HyperTalk",
    "Icon",
    "IDL",
    "Inform",
    "Informix-4GL",
    "INTERCAL",
    "Io",
    "Ioke",
    "J",
    "J#",
    "JADE",
    "Java",
    "Java FX Script",
    "JavaScript",
    "JScript",
    "JScript.NET",
    "Julia",
    "Kaya",
    "Korn Shell",
    "Kotlin",
    "LabVIEW",
    "Ladder Logic",
    "Lasso",
    "Limbo",
    "Lingo",
    "Lisp",
    "LiveScript",
    "Logo",
    "Logtalk",
    "LotusScript",
    "LPC",
    "Lua",
    "Lustre",
    "M4",
    "MAD",
    "Mako",
    "Magic",
    "Magik",
    "Malbolge",
    "MANTIS",
    "Maple",
    "Mathematica",
    "MATLAB",
    "Max/MSP",
    "MAXScript",
    "MEL",
    "Mercury",
    "Mirah",
    "Miva",
    "ML",
    "Monkey",
    "Modula",
    "Modula-2",
    "Modula-3",
    "MOO",
    "Moto",
    "MS-DOS Batch",
    "MUMPS",
    "MXML",
    "N/A",
    "NASM",
    "NATURAL",
    "Nemerle",
    "Nimrod",
    "NQC",
    "NSIS",
    "Nu",
    "NXT-G",
    "Oberon",
    "Object Rexx",
    "Objective-C",
    "Objective-C++",
    "Objective-J",
    "OCaml",
    "Occam",
    "Octave",
    "ooc",
    "Opa",
    "OpenCL",
    "OpenEdge ABL",
    "OPL",
    "Oz",
    "Paradox",
    "Parrot",
    "Pascal",
    "Perl",
    "PHP",
    "Pike",
    "PILOT",
    "PL/I",
    "PL/SQL",
    "Pliant",
    "PostScript",
    "POV-Ray",
    "PowerBasic",
    "PowerScript",
    "PowerShell",
    "Processing",
    "Progress 4GL",
    "Prolog",
    "Puppet",
    "Pure Data",
    "Python",
    "Q",
    "QBasic",
    "QML",
    "R",
    "Racket",
    "Ragel",
    "REALBasic",
    "Red",
    "REBOL",
    "Revolution",
    "REXX",
    "RPG (OS/400)",
    "Ruby",
    "Rust",
    "S",
    "SR",
    "S-PLUS",
    "SAS",
    "Sather",
    "Scala",
    "Scheme",
    "Scilab",
    "Scratch",
    "Scriptol",
    "sed",
    "Seed7",
    "Self",
    "Shell",
    "SIGNAL",
    "Simula",
    "Simulink",
    "Slate",
    "Smalltalk",
    "Smarty",
    "Snobol",
    "SPARK",
    "SPSS",
    "SQL",
    "SQR",
    "Squeak",
    "Squirrel",
    "Standard ML",
    "Suneido",
    "SuperCollider",
    "Swift",
    "SWIG",
    "TACL",
    "Tcl",
    "Tcsh",
    "Tex",
    "thinBasic",
    "TOM",
    "Transact-SQL",
    "Turing",
    "TypeScript",
    "Vala/Genie",
    "VBScript",
    "Velocity",
    "Verilog",
    "VHDL",
    "VimL",
    "Visual Basic .NET",
    "Visual FoxPro",
    "WebDNA",
    "Whitespace",
    "X10",
    "xBase",
    "XBase++",
    "XBasic",
    "Xen",
    "XML",
    "XPL",
    "XSLT",
    "XQuery",
    "yacc",
    "Yorick",
    "Z shell",
)
