# Generated by Django 4.2.8 on 2023-12-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_portfolio", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scancodeproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("importing", "Import Started"),
                    ("success", "Completed"),
                    ("failure", "Failure"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
