# Generated by Django 5.0.6 on 2024-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0006_productdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdependency',
            name='declared_dependency',
            field=models.CharField(blank=True, help_text='A dependency as stated in a project manifest or lockfile, which may be required or optional, and may be associated with specific version ranges.', max_length=1024),
        ),
    ]
