# Generated by Django 5.0.6 on 2024-09-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0006_productdependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancodeproject',
            name='type',
            field=models.CharField(choices=[('IMPORT_FROM_MANIFEST', 'Import from Manifest'), ('LOAD_SBOMS', 'Load SBOMs'), ('PULL_FROM_SCANCODEIO', 'Pull from ScanCode.io'), ('IMPROVE_FROM_PURLDB', 'Improve from PurlDB')], db_index=True, help_text='The type of import, for the ProjectType choices.', max_length=50),
        ),
    ]
