# Generated by Django 5.0.6 on 2024-07-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_portfolio", "0006_productdependency_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productdependency",
            name="product_portfolio_productdependency_unique_dependency_uid_within_product",
        ),
        migrations.RemoveConstraint(
            model_name="productdependency",
            name="product_portfolio_productdependency_unique_uuid_within_dataspace",
        ),
    ]
