# Generated by Django 5.0.9 on 2024-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0008_productdependency_is_resolved_to_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vulnerabilities_risk_threshold',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Enter a risk value between 0.0 and 10.0. This threshold helps prioritize and control the level of attention to vulnerabilities.', max_digits=3, null=True),
        ),
    ]
