# Generated by Django 5.0.9 on 2024-12-24 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0009_product_vulnerabilities_risk_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomponent',
            name='weighted_risk_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Risk score from 0.0 to 10.0, with higher values indicating greater vulnerability risk. This score is the maximum of the weighted severity multiplied by exploitability, capped at 10, which is then multiplied by the associated exposure risk factor assigned to the product item purpose (when available).', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='productitempurpose',
            name='exposure_factor',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='A number between 0.0 and 1.0 that identifies the vulnerability exposure risk of a package as it is actually used in the context of a product, with 1.0 being the highest exposure risk and 0.0 being no exposure risk at all.', max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='weighted_risk_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Risk score from 0.0 to 10.0, with higher values indicating greater vulnerability risk. This score is the maximum of the weighted severity multiplied by exploitability, capped at 10, which is then multiplied by the associated exposure risk factor assigned to the product item purpose (when available).', max_digits=3, null=True),
        ),
    ]
