# Generated by Django 5.1.6 on 2025-02-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('product_portfolio', '0010_productcomponent_weighted_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner is the creator or maintainer of a product, typically the current copyright holder. This field is optional but recommended.', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.owner'),
        ),
    ]
