# Generated by Django 5.1.6 on 2025-02-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0011_alter_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancodeproject',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('importing', 'Import Started'), ('success', 'Completed'), ('failure', 'Failure'), ('warning', 'Warning')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='scancodeproject',
            name='type',
            field=models.CharField(choices=[('IMPORT_FROM_MANIFEST', 'Import Package manifests'), ('LOAD_SBOMS', 'Import SBOM'), ('PULL_FROM_SCANCODEIO', 'Import ScanCode.io project'), ('IMPROVE_FROM_PURLDB', 'Improve from PurlDB'), ('IMPORT_SCAN_RESULTS', 'Import ScanCode scan results')], db_index=True, help_text='The type of import, for the ProjectType choices.', max_length=50),
        ),
    ]
