# Generated by Django 5.1.9 on 2025-05-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0011_alter_component_owner'),
        ('product_portfolio', '0012_alter_scancodeproject_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstatus',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks this product version as read-only, preventing any modifications to its inventory.', verbose_name='Locked inventory'),
        ),
        migrations.AlterField(
            model_name='productdependency',
            name='for_package',
            field=models.ForeignKey(blank=True, help_text='The package that declares this dependency.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declared_dependencies', to='component_catalog.package'),
        ),
        migrations.AlterField(
            model_name='productdependency',
            name='resolved_to_package',
            field=models.ForeignKey(blank=True, help_text='The resolved package for this dependency. If empty, it indicates the dependency is unresolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_from_dependencies', to='component_catalog.package'),
        ),
    ]
