# Generated by Django 5.2.8 on 2025-12-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_portfolio", "0013_productstatus_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scancodeproject",
            name="infer_download_urls",
            field=models.BooleanField(default=False),
        ),
    ]
