# Generated by Django 6.0.4 on 2026-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0015_product_risk_score_productaffectedbyvulnerability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='weighted_risk_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text="Risk score (0.0 to 10.0), where higher values indicate greater vulnerability. Calculated as the weighted severity times exploitability (capped at 10), adjusted by the exposure risk factor of the product item's purpose.", max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='weighted_risk_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text="Risk score (0.0 to 10.0), where higher values indicate greater vulnerability. Calculated as the weighted severity times exploitability (capped at 10), adjusted by the exposure risk factor of the product item's purpose.", max_digits=3, null=True),
        ),
    ]
