# Generated by Django 6.0.5 on 2026-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0016_alter_productcomponent_weighted_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scancodeproject',
            name='import_options',
            field=models.JSONField(blank=True, default=dict, help_text='A dictionary of options used to configure the import process. New options can be added here without requiring a database migration.'),
        ),
    ]
