# Generated by Django 6.0.6 on 2026-07-15 08:25

import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0016_dataspaceconfiguration_policy_rules_config'),
        ('product_portfolio', '0017_scancodeproject_import_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPolicyViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('violation_count', models.PositiveIntegerField(default=0, help_text='Number of objects currently violating the rule.')),
                ('detected_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when this violation was first detected.')),
                ('last_checked', models.DateTimeField(auto_now=True, help_text='The date and time of the last evaluation.')),
                ('resolved', models.BooleanField(default=False, help_text='Indicates whether this violation has been resolved.')),
                ('resolved_date', models.DateTimeField(blank=True, help_text='The date and time when this violation was resolved.', null=True)),
                ('rule_type', models.CharField(help_text='The rule type from the rule registry that triggered this violation.', max_length=50)),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
                ('product', models.ForeignKey(help_text='The product in the context of which this violation was detected.', on_delete=django.db.models.deletion.CASCADE, related_name='policy_violations', to='product_portfolio.product')),
            ],
            options={
                'ordering': ['-detected_date'],
                'unique_together': {('dataspace', 'uuid'), ('rule_type', 'product')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
    ]
