# Generated by Django 6.0.6 on 2026-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_portfolio', '0019_productaffectedbyvulnerability_detected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest_non_vulnerable_version',
            field=models.CharField(blank=True, help_text='The latest available version that is not vulnerable.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='next_non_vulnerable_version',
            field=models.CharField(blank=True, help_text='The next version, following this one, that is not vulnerable.', max_length=100),
        ),
    ]
