# Generated by Django 4.2.7 on 2023-11-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product_portfolio", "0001_initial"),
        ("policy", "0001_initial"),
        ("dje", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagepolicy",
            name="associated_product_relation_status",
            field=models.ForeignKey(
                blank=True,
                help_text="An associated product relation status enables you to specify the product relation status to use automatically when a component or package with an assigned usage policy is added to a product, overriding the general default defined in the product relation status table.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="product_portfolio.productrelationstatus",
            ),
        ),
        migrations.AddField(
            model_name="usagepolicy",
            name="content_type",
            field=models.ForeignKey(
                help_text="Object type identifies the application object (License, Component, Subcomponent relationship, Package) to which the Usage Policy will apply.",
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label", "component_catalog"), ("model", "component")
                    ),
                    models.Q(
                        ("app_label", "component_catalog"), ("model", "subcomponent")
                    ),
                    models.Q(("app_label", "component_catalog"), ("model", "package")),
                    models.Q(("app_label", "license_library"), ("model", "license")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
                verbose_name="object type",
            ),
        ),
        migrations.AddField(
            model_name="usagepolicy",
            name="dataspace",
            field=models.ForeignKey(
                editable=False,
                help_text="A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.",
                on_delete=django.db.models.deletion.PROTECT,
                to="dje.dataspace",
            ),
        ),
        migrations.AddField(
            model_name="associatedpolicy",
            name="dataspace",
            field=models.ForeignKey(
                editable=False,
                help_text="A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.",
                on_delete=django.db.models.deletion.PROTECT,
                to="dje.dataspace",
            ),
        ),
        migrations.AddField(
            model_name="associatedpolicy",
            name="from_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_policies",
                to="policy.usagepolicy",
            ),
        ),
        migrations.AddField(
            model_name="associatedpolicy",
            name="to_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_policies",
                to="policy.usagepolicy",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usagepolicy",
            unique_together={
                ("dataspace", "content_type", "label"),
                ("dataspace", "uuid"),
            },
        ),
        migrations.AlterUniqueTogether(
            name="associatedpolicy",
            unique_together={("from_policy", "to_policy"), ("dataspace", "uuid")},
        ),
    ]
