# Generated by Django 6.0.6 on 2026-07-08 08:39

import django.db.models.deletion
import dje.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0015_alter_dataspaceconfiguration_purldb_api_key_and_more'),
        ('policy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(help_text='Descriptive name for this policy rule.', max_length=100)),
                ('rule_type', models.CharField(help_text='The type of evaluation performed by this rule.', max_length=50)),
                ('threshold', models.PositiveIntegerField(default=0, help_text='Minimum number of violations required to trigger this rule (0 means any).')),
                ('is_active', models.BooleanField(default=True, help_text='Only active rules are evaluated.')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Optional rule-specific parameters as a JSON object. Supported keys depend on the chosen rule type.')),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('dataspace', 'name'), ('dataspace', 'uuid')},
            },
            bases=(dje.models.DataspaceForeignKeyValidationMixin, models.Model),
        ),
    ]
