# Generated by Django 5.2.4 on 2025-07-30 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0008_dataspaceconfiguration_github_token'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttemplate',
            name='issue_tracker_id',
            field=models.CharField(blank=True, help_text='Link to associated issue in a tracking application, provided by the integration when the issue is created.', max_length=1000, verbose_name='Issue Tracker ID'),
        ),
        migrations.CreateModel(
            name='ExternalIssueLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('jira', 'Jira'), ('sourcehut', 'SourceHut'), ('forgejo', 'Forgejo')], help_text='External issue tracking platform.', max_length=20)),
                ('repo', models.CharField(help_text="Repository or project identifier (e.g., 'user/repo-name').", max_length=100)),
                ('issue_id', models.CharField(help_text='ID or key of the issue on the external platform.', max_length=100)),
                ('dataspace', models.ForeignKey(editable=False, help_text='A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.', on_delete=django.db.models.deletion.PROTECT, to='dje.dataspace')),
            ],
            options={
                'unique_together': {('dataspace', 'platform', 'repo', 'issue_id'), ('dataspace', 'uuid')},
            },
        ),
        migrations.AddField(
            model_name='request',
            name='external_issue',
            field=models.ForeignKey(blank=True, help_text='Link to external issue (GitHub, GitLab, Jira, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.externalissuelink'),
        ),
    ]
