# Generated by Django 5.2.4 on 2025-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_requesttemplate_issue_tracker_id_externalissuelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalissuelink',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL of the external issue tracker platform (e.g., https://forgejo.example.org). Used to construct API endpoints for integrations like Forgejo or Jira.', max_length=255, null=True),
        ),
    ]
