# Generated by Django 4.2.7 on 2023-11-27 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("component_catalog", "0001_initial"),
        ("dje", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcomponentassignedlicense",
            name="dataspace",
            field=models.ForeignKey(
                editable=False,
                help_text="A Dataspace is an independent, exclusive set of DejaCode data, which can be either nexB master reference data or installation-specific data.",
                on_delete=django.db.models.deletion.PROTECT,
                to="dje.dataspace",
            ),
        ),
    ]
