# Generated by Django 5.0.6 on 2024-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component_catalog", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="concluded_license",
        ),
        migrations.RemoveField(
            model_name="package",
            name="declared_license",
        ),
        migrations.AddField(
            model_name="component",
            name="declared_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from statements in the manifests or key files of a software project, such as the NOTICE, COPYING, README, and LICENSE files.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="other_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from detected licenses in the non-key files of a software project, which are often third-party software used by the project, or test, sample and documentation files.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="declared_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from statements in the manifests or key files of a software project, such as the NOTICE, COPYING, README, and LICENSE files.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="other_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from detected licenses in the non-key files of a software project, which are often third-party software used by the project, or test, sample and documentation files.",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="license_expression",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='The License Expression assigned to a DejaCode Package or Component is an editable value equivalent to a "concluded license" as determined by a curator who has performed analysis to clarify or correct the declared license expression, which may have been assigned automatically (from a scan or an associated package definition) when the Package or Component was originally created. A license expression defines the relationship of one or more licenses to a software object. More than one applicable license can be expressed as "license-key-a AND license-key-b". A choice of applicable licenses can be expressed as "license-key-a OR license-key-b", and you can indicate the primary (preferred) license by placing it first, on the left-hand side of the OR relationship. The relationship words (OR, AND) can be combined as needed, and the use of parentheses can be applied to clarify the meaning; for example "((license-key-a AND license-key-b) OR (license-key-c))". An exception to a license can be expressed as "license-key WITH license-exception-key".',
                max_length=1024,
                verbose_name="Concluded license expression",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="license_expression",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='The License Expression assigned to a DejaCode Package or Component is an editable value equivalent to a "concluded license" as determined by a curator who has performed analysis to clarify or correct the declared license expression, which may have been assigned automatically (from a scan or an associated package definition) when the Package or Component was originally created. A license expression defines the relationship of one or more licenses to a software object. More than one applicable license can be expressed as "license-key-a AND license-key-b". A choice of applicable licenses can be expressed as "license-key-a OR license-key-b", and you can indicate the primary (preferred) license by placing it first, on the left-hand side of the OR relationship. The relationship words (OR, AND) can be combined as needed, and the use of parentheses can be applied to clarify the meaning; for example "((license-key-a AND license-key-b) OR (license-key-c))". An exception to a license can be expressed as "license-key WITH license-exception-key".',
                max_length=1024,
                verbose_name="Concluded license expression",
            ),
        ),
    ]
