# Generated by Django 5.0.6 on 2024-06-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("component_catalog", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="declared_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from statements in the key files of a software project, such as the NOTICE, COPYING, README, and LICENSE files.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="declared_license_expression_spdx",
            field=models.TextField(
                blank=True,
                help_text="A declared license expression that uses the license identifiers defined by SPDX, as well as the “Licenseref” syntax for licenses not on the SPDX list.",
                verbose_name="Declared license expression SPDX",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="extracted_license_statement",
            field=models.TextField(
                blank=True,
                help_text="The actual text extracted from a software project that supports the license detection process.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="license_detections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of specific license identifiers derived from statements in the key files of a software project, such as the NOTICE, COPYING, README, and LICENSE files.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="other_license_detections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of specific license identifiers derived from the non-key files of a software project, which are very often third-party software used by the project, or test, sample and documentation files.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="other_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from detected licenses in the non-key files of a software project, which are often third-party software used by the project, or test, sample and documentation files.",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="other_license_expression_spdx",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from detected licenses in the non-key files of a software project, using the license identifiers defined by SPDX, as well as the “Licenseref” syntax for licenses not on the SPDX list.",
                verbose_name="Other license expression SPDX",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="declared_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from statements in the key files of a software project, such as the NOTICE, COPYING, README, and LICENSE files.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="declared_license_expression_spdx",
            field=models.TextField(
                blank=True,
                help_text="A declared license expression that uses the license identifiers defined by SPDX, as well as the “Licenseref” syntax for licenses not on the SPDX list.",
                verbose_name="Declared license expression SPDX",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="extracted_license_statement",
            field=models.TextField(
                blank=True,
                help_text="The actual text extracted from a software project that supports the license detection process.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="license_detections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of specific license identifiers derived from statements in the key files of a software project, such as the NOTICE, COPYING, README, and LICENSE files.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="other_license_detections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of specific license identifiers derived from the non-key files of a software project, which are very often third-party software used by the project, or test, sample and documentation files.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="other_license_expression",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from detected licenses in the non-key files of a software project, which are often third-party software used by the project, or test, sample and documentation files.",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="other_license_expression_spdx",
            field=models.TextField(
                blank=True,
                help_text="A license expression derived from detected licenses in the non-key files of a software project, using the license identifiers defined by SPDX, as well as the “Licenseref” syntax for licenses not on the SPDX list.",
                verbose_name="Other license expression SPDX",
            ),
        ),
    ]
