# Generated by Django 5.0.6 on 2024-09-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0007_vulnerability_fixed_packages_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='affected_by_vulnerabilities',
        ),
        migrations.RemoveField(
            model_name='component',
            name='affected_by_vulnerabilities',
        ),
        migrations.DeleteModel(
            name='Vulnerability',
        ),
    ]
