# Generated by Django 5.0.9 on 2024-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0009_componentaffectedbyvulnerability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Risk score between 0.0 and 10.0, where higher values indicate greater vulnerability risk for the package.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Risk score between 0.0 and 10.0, where higher values indicate greater vulnerability risk for the package.', max_digits=3, null=True),
        ),
    ]
