# Generated by Django 5.0.9 on 2024-11-12 08:13

from django.db import migrations
from django.db.models import Count


def generate_random_risk_score():
    import random
    from decimal import Decimal

    return Decimal(f"{random.uniform(0, 10):.2f}")


def set_random_risk_score(apps, schema_editor):
    Package = apps.get_model("component_catalog", "Package")

    qs = Package.objects.annotate(
        vulnerability_count=Count("affected_by_vulnerabilities", distinct=True)
    ).filter(vulnerability_count__gt=0)

    for package in qs:
        risk_score = generate_random_risk_score()
        Package.objects.filter(pk=package.pk).update(risk_score=risk_score)


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0010_component_risk_score_package_risk_score'),
    ]

    operations = [
        migrations.RunPython(set_random_risk_score, reverse_code=migrations.RunPython.noop),
    ]
