# Generated by Django 5.1.6 on 2025-02-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0010_component_risk_score_package_risk_score'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner is the creator or maintainer of a component, typically the current copyright holder. This field is optional but recommended.', null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.owner'),
        ),
    ]
