# Generated by Django 5.2.4 on 2025-07-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0011_alter_component_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='children',
            field=models.ManyToManyField(through='component_catalog.Subcomponent', through_fields=('parent', 'child'), to='component_catalog.component'),
        ),
    ]
