# Generated by Django 5.1.8 on 2025-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0011_alter_component_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_content',
            field=models.IntegerField(choices=[(1, 'curation'), (2, 'patch'), (3, 'source_repo'), (4, 'source_archive'), (5, 'binary'), (6, 'test'), (7, 'doc')], help_text='Content of this package as one of: curation, patch, source_repo, source_archive, binary, test, doc', null=True),
        ),
    ]
