# Generated by Django 5.0.9 on 2024-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0012_alter_component_risk_score_alter_package_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Risk score between 0.0 and 10.0, where higher values indicate greater vulnerability risk for the package.', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Risk score between 0.0 and 10.0, where higher values indicate greater vulnerability risk for the package.', max_digits=3, null=True),
        ),
    ]
