# Generated by Django 5.2.8 on 2025-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0012_alter_component_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_content',
            field=models.IntegerField(blank=True, choices=[(1, 'curation'), (2, 'patch'), (3, 'source_repo'), (4, 'source_archive'), (5, 'binary'), (6, 'test'), (7, 'doc')], help_text='Content of this Package as one of: curation, patch, source_repo, source_archive, binary, test, doc', null=True),
        ),
    ]
