# Generated by Django 6.1.1 on 2026-10-09 07:47

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_catalog', '0015_component_latest_non_vulnerable_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='vcs_url',
            field=models.CharField(blank=True, help_text='URL to the Version Control System (VCS).', max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+.-]+://[\\S]+$'), code='invalid', message='Enter a valid URI.')], verbose_name='VCS URL'),
        ),
        migrations.AlterField(
            model_name='package',
            name='download_url',
            field=models.CharField(blank=True, help_text='The download URL for obtaining the package.', max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+.-]+://[\\S]+$'), code='invalid', message='Enter a valid URI.')], verbose_name='Download URL'),
        ),
        migrations.AlterField(
            model_name='package',
            name='vcs_url',
            field=models.CharField(blank=True, help_text='URL to the Version Control System (VCS).', max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^[\\w+.-]+://[\\S]+$'), code='invalid', message='Enter a valid URI.')], verbose_name='VCS URL'),
        ),
    ]
