#!/bin/sh
#
# Copyright (c) nexB Inc. and others. All rights reserved.
# DejaCode is a trademark of nexB Inc.
# SPDX-License-Identifier: AGPL-3.0-only
# See https://github.com/aboutcode-org/dejacode for support or download.
# See https://aboutcode.org for more information about AboutCode FOSS projects.
#

# Copy this file in .git/hooks/ to trigger the code validation on commit
# cp etc/git_hooks/pre-commit .git/hooks/pre-commit
# chmod +x .git/hooks/pre-commit

make valid
