name: Check code and docs validation

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-code-and-docs-validation:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false  # do not keep the token around

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.14"

      - name: Install uv from vendored wheel
        run: pip install --no-index --find-links=./thirdparty/dist uv

      - name: Validate code format
        run: make check

      - name: Build the documentation
        run: make docs
