name: Create a GitHub release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-github-release:
    runs-on: ubuntu-24.04

    steps:
      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          files: dist/*
