name: Create a GitHub release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-github-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # needed to create releases and upload assets

    steps:
      - name: Create a GitHub release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # v2.5.0
        with:
          generate_release_notes: true
          draft: false
          files: dist/*
