name: Create a GitHub release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-github-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # needed to create releases and upload assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Create a GitHub release
        run: gh release create "$GITHUB_REF_NAME" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
