name: Find dependencies vulnerabilities

on: [push]

jobs:
  scan-codebase:
    runs-on: ubuntu-24.04
    name: Inspect packages with ScanCode.io
    steps:
      - uses: actions/checkout@v4
        with:
          path: scancode-inputs
          sparse-checkout: setup.cfg
          sparse-checkout-cone-mode: false

      - uses: nexB/scancode-action@alpha
        with:
          pipelines: "inspect_packages:StaticResolver,find_vulnerabilities"
        env:
          VULNERABLECODE_URL: https://public.vulnerablecode.io/

      - name: Fail in case of vulnerabilities
        shell: bash
        run: |
          scanpipe shell --command '
          from scanpipe.models import Project
          project = Project.objects.get()
          vulnerability_count = (
              project.discoveredpackages.vulnerable().count() +
              project.discovereddependencies.vulnerable().count()
          )
          print(vulnerability_count, "vulnerabilities found")
          exit(1) if vulnerability_count else exit(0)
          '
