name: Create a GitHub release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-github-release:
    runs-on: ubuntu-22.04

    steps:
      - name: Create a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
