name: Run unit tests on Docker container

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate the .env file and the SECRET_KEY
        run: make envfile

      - name: Run tests
        run: docker compose run web python ./manage.py test --verbosity=2 --noinput
