# Generated by Django 5.0.9 on 2024-11-12 08:13

from django.db import migrations
import random
from decimal import Decimal


def set_random_risk_score(apps, schema_editor):
    Vulnerability = apps.get_model("vulnerabilities", "Vulnerability")

    qs = Vulnerability.objects.all()
    for vulnerability in qs:
        exploitability = random.choice([0.5, 1.0, 2.0])  # 0.5, 1.0, or 2.0
        weighted_severity = Decimal(f"{random.uniform(0, 10):.2f}")  # 0 to 10
        risk_score = f"{min(float(exploitability) * float(weighted_severity), 10.0):.2f}"

        Vulnerability.objects.filter(pk=vulnerability.pk).update(
            exploitability=exploitability,
            weighted_severity=weighted_severity,
            risk_score=risk_score,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_remove_vulnerability_max_score_and_more'),
    ]

    operations = [
        migrations.RunPython(set_random_risk_score, reverse_code=migrations.RunPython.noop),
    ]
