# Generated by Django 6.0.6 on 2026-06-15 14:51

import dje.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0007_vulnerability_vulnerabili_exploit_f83324_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vulnerability',
            name='vulnerabili_vulnera_92f044_idx',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='advisory_id',
            field=models.CharField(help_text='An advisory is a vulnerability identifier in some database, such as PYSEC-2020-2233', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='advisory_uid',
            field=models.CharField(help_text='Unique ID for the datasource used for this advisory .e.g.: pysec_importer_v2/PYSEC-2020-2233', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ssvc_trees',
            field=dje.fields.JSONListField(blank=True, default=list, help_text='A list of SSVC decision trees for this vulnerability.'),
        ),
    ]
