# Generated by Django 6.0.4 on 2026-06-10

from django.db import migrations, models
import dje.fields


def purge_vulnerabilities(apps, schema_editor):
    """Purge all Vulnerability rows before adding non-nullable advisory fields."""
    Vulnerability = apps.get_model("vulnerabilities", "Vulnerability")
    Vulnerability.objects.all().delete()


class Migration(migrations.Migration):
    # Non-atomic: the purge step cascades FK deletes which leave pending trigger
    # events that block subsequent ALTER TABLE in the same transaction.
    atomic = False

    dependencies = [
        ("vulnerabilities", "0007_vulnerability_vulnerabili_exploit_f83324_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(purge_vulnerabilities, migrations.RunPython.noop),
        # Remove old unique_together referencing vulnerability_id before dropping the field.
        migrations.AlterUniqueTogether(
            name="vulnerability",
            unique_together={("dataspace", "uuid")},
        ),
        migrations.RemoveIndex(
            model_name="vulnerability",
            name="vulnerabili_vulnera_92f044_idx",
        ),
        migrations.RemoveField(
            model_name="vulnerability",
            name="vulnerability_id",
        ),
        # noop forward; backward: purge rows before re-adding NOT NULL vulnerability_id.
        migrations.RunPython(migrations.RunPython.noop, purge_vulnerabilities),
        migrations.RemoveField(
            model_name="vulnerability",
            name="references",
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="advisory_uid",
            field=models.CharField(
                help_text="Unique ID for the datasource used for this advisory ."
                "e.g.: pysec_importer_v2/PYSEC-2020-2233",
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="advisory_id",
            field=models.CharField(
                help_text="An advisory is a vulnerability identifier in some database, "
                "such as PYSEC-2020-2233",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='ssvc_trees',
            field=dje.fields.JSONListField(
                blank=True, default=list, help_text='A list of SSVC decision trees for this vulnerability.'
                ),
        ),
        # Restore unique_together with the new advisory_uid field.
        migrations.AlterUniqueTogether(
            name="vulnerability",
            unique_together={("dataspace", "uuid"), ("dataspace", "advisory_uid")},
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(fields=['advisory_uid'], name='vulnerabili_advisor_8c2f81_idx'),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(fields=["advisory_id"], name="vulnerabili_advisor_7de61b_idx"),
        ),
    ]
