# Generated by Django 6.0.6 on 2026-06-15 12:28

import dje.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0008_purge_and_add_advisory_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='ssvc_trees',
            field=dje.fields.JSONListField(blank=True, default=list, help_text='A list of SSVC decision trees for this vulnerability.'),
        ),
    ]
