# Generated by Django 6.0.6 on 2026-06-15 14:53

from django.db import migrations
from django.db.models import F


def migrate_and_purge_vulnerabilities(apps, schema_editor):
    """
    Migrate vulnerability_id to advisory_id/advisory_uid for vulnerabilities
    linked to a VulnerabilityAnalysis, then purge the rest.
    vulnerability_id was unique so using it directly as both fields is safe.
    """
    Vulnerability = apps.get_model("vulnerabilities", "Vulnerability")
    VulnerabilityAnalysis = apps.get_model("vulnerabilities", "VulnerabilityAnalysis")

    linked_ids = VulnerabilityAnalysis.objects.values_list(
        "vulnerability_id", flat=True
    ).distinct()

    Vulnerability.objects.filter(id__in=linked_ids).update(
        advisory_id=F("vulnerability_id"),
        advisory_uid=F("vulnerability_id"),
    )

    Vulnerability.objects.exclude(id__in=linked_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0008_api_v3_new_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_and_purge_vulnerabilities, migrations.RunPython.noop),
    ]
