# Generated by Django 6.0.6 on 2026-06-15 14:53

from django.db import migrations


def purge_vulnerabilities(apps, schema_editor):
    """Purge all Vulnerability rows before adding non-nullable advisory fields."""
    Vulnerability = apps.get_model("vulnerabilities", "Vulnerability")
    Vulnerability.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0008_api_v3_new_fields'),
    ]

    operations = [
        migrations.RunPython(purge_vulnerabilities, migrations.RunPython.noop),
    ]
