# Generated by Django 6.0.6 on 2026-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dje', '0015_alter_dataspaceconfiguration_purldb_api_key_and_more'),
        ('vulnerabilities', '0009_api_v3_data_migrations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vulnerability',
            unique_together={('dataspace', 'advisory_uid'), ('dataspace', 'uuid')},
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='advisory_id',
            field=models.CharField(help_text='An advisory is a vulnerability identifier in some database, such as PYSEC-2020-2233', max_length=200),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='advisory_uid',
            field=models.CharField(help_text='Unique ID for the datasource used for this advisory .e.g.: pysec_importer_v2/PYSEC-2020-2233', max_length=250),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['advisory_uid'], name='vulnerabili_advisor_8c2f81_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['advisory_id'], name='vulnerabili_advisor_7de61b_idx'),
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='references',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='vulnerability_id',
        ),
    ]
